name: Localization test

on:
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: ./l10n

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.11 ]

    steps:
      - name: Set up project
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install sl10n
        run: pip install sl10n
      - name: Install pytest and run test
        run: |
          pip install pytest
          pytest -q test.py
